pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
            
            stage('ContDeployment')
        {
            steps
            {
               sshagent(['tomcat-cred']) {
        sh 'scp -o StrictHostKeyChecking=no /var/lib/jenkins/workspace/first-job/webapp/target/my-app-1.0-SNAPSHOT.jar ec2-user@172.31.89.204:/opt/apache-tomcat-8.5.43/webapps/'
                        
                   
             }
        }
    }
}
